### ISSUE TITLE
Float is forced for custom bins

### ISSUE THREAD

**Issue by voska** [jtprince/histogram#10]
I'm trying to keep everything in integers, but they are being forced into floats.
<img width="410" alt="screen shot 2015-12-25 at 03 53 14" src="https://cloud.githubusercontent.com/assets/3444419/12002042/1027cfa6-aabb-11e5-93bd-6990ffe33617.png">

**Comment by jtprince** [comment]
Sorry for the late reply.  What you are seeing is the expected behavior.  The vast majority of use cases for this gem involve instances where we want either fast histogram behavior (so need floats) or deal in non-discrete data (so, need to be able to handle floats).  In your case, the data is being histogrammed using a constant time float transformation.  Of course, with a small dataset, or with a discrete dataset, this behavior buys you nothing.

If you want to maintain integers then there are many ways to achieve this in a single line of code:
https://stackoverflow.com/questions/5857915/ruby-unique-elements-in-array

I'm open to the idea of some kind of :discrete option which would just implement one of those above but give the data in a form consistent with the histogram gem.  If you think that would be worth pursuing, just open another issue as a feature request, if you don't mind.
