### ISSUE TITLE
No values returned from `.histogram`

### ISSUE THREAD

**Issue by duhaime** [jtprince/histogram#12]
Hi all, I'm not sure if anyone is looking at this repo anymore, but on Ruby 3.2.2 with the latest from RubyGems I'm seeing:

```
Hello (DEVELOPMENT) > (bins, freqs) = [1,2,2,2,3,3,3,4,4,4].histogram(2)
+-------+-------+
| value | count |
+-------+-------+
| 4     | 3     |
| 3     | 3     |
+-------+-------+
2 rows in set
And 2 additional rows omitted
=> nil
Hello (DEVELOPMENT) > bins
=> nil
Hello (DEVELOPMENT) > freqs
=> nil
```

Do I need to pass a flag to get the values to return?

**Comment by jtprince** [comment]
I still maintain the repo to some extent (ended up switching to python as main driver because of drafting coefficient, but I still love ruby and like to contribute to her success).

There may be some confusion about what it is that the histogram function is trying to do (or possibly there is a collision with another histogram implementation?).  This is what I'm seeing on fresh installs of ruby and histogram:

```ruby
$ irb
>> RUBY_VERSION
=> "3.2.2"
>> require 'histogram/array'
=> true
>> (bins, freqs) = [1,2,2,2,3,3,3,4,4,4].histogram(2)
=> [[1.75, 3.25], [4.0, 6.0]]

$ irb
>> RUBY_VERSION
=> "2.7.8"
>> require 'histogram/array'
=> true
>> (bins, freqs) = [1,2,2,2,3,3,3,4,4,4].histogram(2)
=> [[1.75, 3.25], [4.0, 6.0]]
```

And this is the _expected_ behavior, I think (the request was for 2 bins to a _numeric_ histogram). There aren't additional rows because there should only be two bins?

Are you tying to achieve a [multiset/Counter like behavior](https://stackoverflow.com/questions/33828449/equivalent-of-pythons-counter-in-ruby), so [something like this](http://www.java2s.com/Code/Ruby/Collections/BuildingaHistogram.htm)?  How did you generate the output in your issue post?  It doesn't look like it emanated from this histogram library?

Happy to help!

**Comment by duhaime** [comment]
Ah great, so this seems like something in my environment. 

In Ruby how can I see where this `histogram` method is bound to the array?

**Comment by jtprince** [comment]
> In Ruby how can I see where this histogram method is bound to the array?

I poked around a bit and couldn't figure out how to do this, sorry.  I would probably approach this by looking at my bundle and looking for other histogram related packages and/or grepping for "histogram" in my code base and/or associated libs.

Going to close this particular issue since at this point it transcends the original issue (and goes beyond my expertise to help much, apologies).
